### ISSUE TITLE
Error: No native build was found 

### ISSUE THREAD

**Issue by nichoth** [staltz/node-bindgen-loader#1]
This error originates a few levels deep, from [ssb-db2 originally](https://github.com/ssb-ngi-pointer/ssb-db2/issues/294), but this is the root module causing it. I'm not sure how to debug this.

```
Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=93 uv=1 armv=8 libc=glibc node=16.13.1
```

__full message:__

```
ssb-db2 master % npm test

> ssb-db2@2.8.3 test
> tape test/*.js | tap-spec

/Users/nick/code/ssb-db2/node_modules/node-bindgen-loader/index.js:62
  throw new Error('No native build was found for ' + target + '\n    loaded from: ' + dir + '\n')
  ^

Error: No native build was found for platform=darwin arch=arm64 runtime=node abi=93 uv=1 armv=8 libc=glibc node=16.13.1
    loaded from: /Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node

    at Function.load.path (/Users/nick/code/ssb-db2/node_modules/node-bindgen-loader/index.js:62:9)
    at load (/Users/nick/code/ssb-db2/node_modules/node-bindgen-loader/index.js:27:30)
    at Object.<anonymous> (/Users/nick/code/ssb-db2/node_modules/ssb-validate2-rsjs-node/index.js:5:41)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/nick/code/ssb-db2/db.js:10:7)
```

**Comment by staltz** [comment]
I think the error itself is just a warning, and afterwards it *should* attempt to compile the module (in that case, with `nj-cli`).

**Comment by nichoth** [comment]
thanks @staltz 

I think the next thing I will look into is if it does indeed attempt to compile it. I'm using this with [ssb-validate2-rsjs-node](https://github.com/ssb-ngi-pointer/ssb-validate2-rsjs-node/issues/17). 

The bad news is that I don't really know what's going on here. So there is a rust library, and we are trying to use a compiled version of it with a node library. And this repo is responsible for making a compiled version.
